#!/usr/bin/with-contenv bash

PUID=${PUID:-2000}
PGID=${PGID:-2000}

groupmod -o -g "$PGID" appuser
usermod -o -u "$PUID" appuser

chown -R appuser:appuser /config

echo "
-------------------------------------
User uid:        $(id -u appuser)
User gid:        $(id -g appuser)
-------------------------------------
"

